version: '3.8'
services:
  app:
    image: ghcr.io/ferrariroma/nest-app-app:latest
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == worker]
    depends_on:
      - db
    tmpfs:
      - /run
    environment:
      NODE_ENV: production
      DB_HOST_FILE: /run/secrets/DB_HOST
      # DB_HOST: ${DB_HOST}
      DB_USERNAME_FILE: /run/secrets/DB_USERNAME
      # DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD_FILE: /run/secrets/DB_PASSWORD
      # DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT_FILE: /run/secrets/DB_PORT
      # DB_PORT: ${DB_PORT}
      DB_DATABASE_FILE: /run/secrets/DB_DATABASE
      # DB_DATABASE: ${DB_DATABASE}
      OAUTH_ID_FILE: /run/secrets/OAUTH_ID
      # OAUTH_ID: ${OAUTH_ID}
      OAUTH_PW_FILE: /run/secrets/OAUTH_PW
      # OAUTH_PW: ${OAUTH_PW}
      REDIRECT_URL_FILE: /run/secrets/REDIRECT_URL
      # REDIRECT_URL: ${REDIRECT_URL}
    ports:
      - '8080:8080'
    networks:
      - appnet
    secrets:
      # - db_host
      # - db_username
      # - db_password
      # - db_port
      # - db_database
      # - oauth_id
      # - oauth_pw
      # - redirect_url
      - DB_HOST
      - DB_USERNAME
      - DB_PASSWORD
      - DB_PORT
      - DB_DATABASE
      - OAUTH_ID
      - OAUTH_PW
      - REDIRECT_URL
  db:
    image: mysql:latest
    deploy:
      placement:
        constraints: [node.role == worker]
    tmpfs:
      - /run
    environment:
      MYSQL_DATABASE_FILE: /run/secrets/MYSQL_DATABASE
      # MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER_FILE: /run/secrets/MYSQL_USERNAME
      # MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD_FILE: /run/secrets/MYSQL_PASSWORD
      # MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - appnet
    secrets:
      # - mysql_database
      # - mysql_user
      # - mysql_password
      - MYSQL_DATABASE
      - MYSQL_USERNAME
      - MYSQL_PASSWORD
networks:
  appnet:
    driver: overlay
volumes:
  dbdata:
secrets:
  DB_HOST:
    external: true
  DB_USERNAME:
    external: true
  DB_PASSWORD:
    external: true
  DB_PORT:
    external: true
  DB_DATABASE:
    external: true
  OAUTH_ID:
    external: true
  OAUTH_PW:
    external: true
  REDIRECT_URL:
    external: true
  MYSQL_DATABASE:
    external: true
  MYSQL_USERNAME:
    external: true
  MYSQL_PASSWORD:
    external: true
# echo ${{ secrets.DB_HOST }} | docker secret create DB_HOST -
# echo ${{ secrets.DB_USERNAME }} | docker secret create DB_USERNAME -
# echo ${{ secrets.DB_PASSWORD }} | docker secret create DB_PASSWORD -
# echo ${{ secrets.DB_PORT }} | docker secret create DB_PORT -
# echo ${{ secrets.DB_DATABASE }} | docker secret create DB_DATABASE -
# echo ${{ secrets.OAUTH_ID }} | docker secret create OAUTH_ID -
# echo ${{ secrets.OAUTH_PW }} | docker secret create OAUTH_PW -
# echo ${{ secrets.REDIRECT_URL }} | docker secret create REDIRECT_URL -
# echo ${{ secrets.TOKEN_GITHUB }} | docker secret create EXTREME -
# echo ${{ secrets.DB_DATABASE }} | docker secret create MYSQL_DATABASE -
# echo ${{ secrets.DB_USERNAME }} | docker secret create MYSQL_USER -
# echo ${{ secrets.DB_PASSWORD }} | docker secret create MYSQL_PASSWORD -
