FROM node:16.13.1
RUN mkdir -p /app
WORKDIR /app
ADD . /app/
ENV DB_HOST $DB_HOST
ENV DB_PORT $DB_PORT
ENV DB_USERNAME $DB_USERNAME
ENV DB_PASSWORD $DB_PASSWORD
ENV DB_DATABASE $DB_DATABASE
ENV OAUTH_ID $OAUTH_ID
ENV OAUTH_PW $OAUTH_PW
ENV REDIRECT_URL $REDIRECT_URL
RUN npm run build
EXPOSE 8080
ENTRYPOINT npm run start:prod