version: '3'
services:
  app:
    image: ghcr.io/ferrariroma/nest-app-app:latest
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - db
    environment:
      NODE_ENV: production
      DB_HOST: ${DB_HOST}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      OAUTH_ID: ${OAUTH_ID}
      OAUTH_PW: ${OAUTH_PW}
      REDIRECT_URL: ${REDIRECT_URL}
      TZ: UTC
    ports:
      - '8080:8080'
    networks:
      - appnet
  db:
    image: mysql:latest
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      TZ: UTC
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - appnet
networks:
  appnet:
volumes:
  dbdata:
