name: Deploy
on:
  push:
    branches:
      - main
env:
  DB_HOST: ${{ secrets.DB_HOST }}
  DB_USERNAME: ${{ secrets.DB_USERNAME }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  DB_PORT: ${{ secrets.DB_PORT }}
  DB_DATABASE: ${{ secrets.DB_DATABASE }}
  OAUTH_ID: ${{ secrets.OAUTH_ID }}
  OAUTH_PW: ${{ secrets.OAUTH_PW }}
  REDIRECT_URL: ${{ secrets.REDIRECT_URL }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN_GITHUB }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/ferrariroma/nest-app-app:${{ github.sha }}
      - name: Deploy stack to Docker Swarm
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_PUBLIC }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            echo ${{ secrets.DB_HOST }} | docker secret create DB_HOST -
            echo ${{ secrets.DB_USERNAME }} | docker secret create DB_USERNAME -
            echo ${{ secrets.DB_PASSWORD }} | docker secret create DB_PASSWORD -
            echo ${{ secrets.DB_PORT }} | docker secret create DB_PORT -
            echo ${{ secrets.DB_DATABASE }} | docker secret create DB_DATABASE -
            echo ${{ secrets.OAUTH_ID }} | docker secret create OAUTH_ID -
            echo ${{ secrets.OAUTH_PW }} | docker secret create OAUTH_PW -
            echo ${{ secrets.REDIRECT_URL }} | docker secret create REDIRECT_URL -
            echo ${{ secrets.TOKEN_GITHUB }} | docker secret create EXTREME -
            echo ${{ secrets.DB_DATABASE }} | docker secret create MYSQL_DATABASE -
            echo ${{ secrets.DB_USERNAME }} | docker secret create MYSQL_USER -
            echo ${{ secrets.DB_PASSWORD }} | docker secret create MYSQL_PASSWORD -
            echo $EXTREME | docker login ghcr.io -u ferrariRoma --password-stdin
            docker stack deploy -c docker-compose.yml myapp --with-registry-auth
